name: workshops
description: A workshop viewer application
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.0
  image_picker: ^0.6.7+12
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0
  toast: ^0.1.5
  url_launcher: ^5.7.10
  flutter_launcher_icons: ^0.8.0
  data_connection_checker: ^0.3.4
  sembast:
  get_it: ^7.2.0
  path_provider:


  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher.jpg"

flutter:
  uses-material-design: true
  assets:
   - assets/background.jpg
   - assets/college.png
   - assets/info.png
